# Generated by Django 4.0.5 on 2022-06-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_occupation', models.CharField(max_length=200)),
                ('number_of_nights', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('room_number', models.IntegerField(unique=True)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
